on:
    workflow_dispatch:

jobs:
    package:
        name: package
        runs-on: ubuntu-latest
    
        steps:

        - name: checkout
          uses: actions/checkout@master
          with:
            repository: Gauravlwplabs/java-db-Login
        
        - name: Setup JDK 8
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '8'
        
        - name: build package
          run: mvn clean package
    

          
